[project]
name = "regexfilesearcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "auto-py-to-exe>=2.47.0",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "pyside6-essentials>=6.9.2",
    "xlsxwriter>=3.2.5",
]
